# Generated by Django 5.2.4 on 2025-09-01 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('cant_aptos', models.IntegerField()),
                ('cant_bloques', models.IntegerField()),
                ('cant_pisos', models.IntegerField()),
                ('nombre_admin', models.CharField(max_length=50)),
                ('piscina', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('visa', models.IntegerField(choices=[(0, 'Turista'), (1, 'Familiar'), (2, 'Periodista'), (3, 'Estudiante'), (4, 'Negocios'), (5, 'Tratamiento medico')], default='0')),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.propietario')),
            ],
            options={
                'verbose_name': 'Movimiento de Propietario',
                'verbose_name_plural': 'Movimientos de Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bloque', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('cant_habitaciones', models.IntegerField()),
                ('adeudo', models.BooleanField()),
                ('cant_adeudo', models.FloatField()),
                ('fecha_adeudo', models.DateField()),
                ('valla', models.BooleanField()),
                ('numero_valla', models.IntegerField()),
                ('mandato', models.BooleanField()),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edificio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propietario')),
            ],
        ),
    ]
