# Generated by Django 5.2.4 on 2025-09-14 22:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bloque', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('cant_habitaciones', models.IntegerField()),
                ('adeudo', models.BooleanField()),
                ('cant_adeudo', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fecha_adeudo', models.DateField(blank=True, null=True)),
                ('valla', models.BooleanField()),
                ('numero_valla', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mandato', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('cant_aptos', models.IntegerField()),
                ('cant_bloques', models.IntegerField()),
                ('cant_pisos', models.IntegerField()),
                ('nombre_admin', models.CharField(max_length=50)),
                ('piscina', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Conviviente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivientes', to='app.apartamento')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendatarios', to='app.apartamento')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edificio')),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edificio'),
        ),
        migrations.CreateModel(
            name='MovimientoArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7)),
                ('residente_inmobiliario', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('tipo_visa', models.IntegerField(blank=True, choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0, null=True)),
                ('fecha_visa', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.arrendatario')),
            ],
            options={
                'verbose_name': 'Movimiento de Arrendatario',
                'verbose_name_plural': 'Movimientos de Arrendatarios',
            },
        ),
        migrations.CreateModel(
            name='MovimientoConviviente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7)),
                ('residente_inmobiliario', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('tipo_visa', models.IntegerField(blank=True, choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0, null=True)),
                ('fecha_visa', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('conviviente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.conviviente')),
            ],
            options={
                'verbose_name': 'Movimiento de Conviviente',
                'verbose_name_plural': 'Movimientos de Convivientes',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nacionalidad', django_countries.fields.CountryField(default='CU', max_length=2)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
                ('representante', models.BooleanField(default=False)),
                ('rep_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_dni', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_nacionalidad', django_countries.fields.CountryField(blank=True, default='CU', max_length=2, null=True)),
                ('rep_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('rep_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7)),
                ('residente_inmobiliario', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('tipo_visa', models.IntegerField(blank=True, choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0, null=True)),
                ('fecha_visa', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.propietario')),
            ],
            options={
                'verbose_name': 'Movimiento de Propietario',
                'verbose_name_plural': 'Movimientos de Propietarios',
            },
        ),
        migrations.AddField(
            model_name='apartamento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='app.propietario'),
        ),
    ]
