# Generated by Django 5.2.4 on 2025-08-06 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('cant_bloques', models.IntegerField()),
                ('cant_pisos', models.IntegerField()),
                ('nombre_admin', models.CharField(max_length=50)),
                ('piscina', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('visa', models.CharField(choices=[('T', 'Turista'), ('F', 'Familiar'), ('p', 'Periodista'), ('E', 'Estudiante'), ('N', 'Negocios'), ('M', 'Tratamiento medico')], default='T', max_length=1)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bloque', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('cant_habitaciones', models.IntegerField()),
                ('adeudo', models.BooleanField()),
                ('valla', models.BooleanField()),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edificio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propietario')),
            ],
        ),
    ]
