# Generated by Django 5.2.4 on 2025-08-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='visa',
            field=models.CharField(choices=[(0, 'Turista'), (1, 'Familiar'), (2, 'Periodista'), (3, 'Estudiante'), (4, 'Negocios'), (5, 'Tratamiento medico')], default='T', max_length=1),
        ),
    ]
