# Generated by Django 5.2.4 on 2025-09-10 04:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('visa', models.IntegerField(choices=[(0, 'Turista'), (1, 'Familiar'), (2, 'Periodista'), (3, 'Estudiante'), (4, 'Negocios'), (5, 'Tratamiento medico')], default='0')),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('observaciones', models.CharField(max_length=100)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=7)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.arrendatario')),
            ],
            options={
                'verbose_name': 'Movimiento de Arrendatario',
                'verbose_name_plural': 'Movimientos de Arrendatarios',
            },
        ),
    ]
