# Generated by Django 5.2.4 on 2025-08-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_propietario_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='cant_aptos',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
