# Generated by Django 5.2.4 on 2025-09-10 04:26

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_arrendatario_movimientoarrendatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
