# Generated by Django 5.2.4 on 2025-09-10 06:34

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_propietario_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='apartamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.apartamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrendatario',
            name='nacionalidad',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nacionalidad',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
