# Generated by Django 5.2.4 on 2025-08-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_propietario_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='visa',
            field=models.IntegerField(choices=[(0, 'Turista'), (1, 'Familiar'), (2, 'Periodista'), (3, 'Estudiante'), (4, 'Negocios'), (5, 'Tratamiento medico')], default='0', max_length=1),
        ),
    ]
