# Generated by Django 5.2.4 on 2025-09-11 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conviviente_movimientoconviviente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='cant_adeudo',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='fecha_adeudo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero_valla',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
