# Generated by Django 5.2.4 on 2025-09-11 16:38

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_apartamento_cant_adeudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='apellidos',
            field=models.CharField(default='perez', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='rep_apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='rep_dni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='rep_nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='rep_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='rep_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero_valla',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
