# Generated by Django 5.2.4 on 2025-09-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_propietario_apellidos_propietario_rep_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendatario',
            name='apellidos',
            field=models.CharField(default='perez', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conviviente',
            name='apellidos',
            field=models.CharField(default='perez', max_length=50),
            preserve_default=False,
        ),
    ]
