# Generated by Django 5.2.4 on 2025-09-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_arrendatario_apellidos_conviviente_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='representante',
            field=models.BooleanField(default=False),
        ),
    ]
