# Generated by Django 5.2.4 on 2025-09-13 17:31

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_propietario_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='residente_inmobiliario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propietario',
            name='tipo_visa',
            field=models.IntegerField(blank=True, choices=[(0, 'Turista'), (1, 'Familiar'), (2, 'Periodista'), (3, 'Estudiante'), (4, 'Negocios'), (5, 'Tratamiento medico')], default='0', null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nacionalidad',
            field=django_countries.fields.CountryField(default='CU', max_length=2),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='visa',
            field=models.BooleanField(default=False),
        ),
    ]
