# Generated by Django 5.2.4 on 2025-09-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_propietario_residente_inmobiliario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='tipo_visa',
            field=models.IntegerField(blank=True, choices=[(0, 'Turista'), (1, 'Familiar'), (2, 'Periodista'), (3, 'Estudiante'), (4, 'Negocios'), (5, 'Tratamiento medico')], default=0, null=True),
        ),
    ]
