# Generated by Django 5.2.4 on 2025-09-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_propietario_tipo_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendatario',
            name='visa',
            field=models.IntegerField(choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default='0'),
        ),
        migrations.AlterField(
            model_name='conviviente',
            name='visa',
            field=models.IntegerField(choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default='0'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo_visa',
            field=models.IntegerField(blank=True, choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0, null=True),
        ),
    ]
