# Generated by Django 5.2.4 on 2025-09-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_arrendatario_visa_alter_conviviente_visa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendatario',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='conviviente',
            name='visa',
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='tipo_visa',
            field=models.IntegerField(choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0),
        ),
        migrations.AddField(
            model_name='conviviente',
            name='tipo_visa',
            field=models.IntegerField(choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0),
        ),
        migrations.AlterField(
            model_name='arrendatario',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrendatarios', to='app.apartamento'),
        ),
        migrations.AlterField(
            model_name='conviviente',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivientes', to='app.apartamento'),
        ),
    ]
