# Generated by Django 5.2.4 on 2025-09-13 20:59

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_arrendatario_residente_inmobiliario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='app.propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='rep_nacionalidad',
            field=django_countries.fields.CountryField(blank=True, default='CU', max_length=2, null=True),
        ),
    ]
