# Generated by Django 5.2.4 on 2025-09-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_apartamento_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoarrendatario',
            name='residente_inmobiliario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoarrendatario',
            name='tipo_visa',
            field=models.IntegerField(blank=True, choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimientoarrendatario',
            name='visa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoconviviente',
            name='residente_inmobiliario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoconviviente',
            name='tipo_visa',
            field=models.IntegerField(blank=True, choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimientoconviviente',
            name='visa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientopropietario',
            name='residente_inmobiliario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientopropietario',
            name='tipo_visa',
            field=models.IntegerField(blank=True, choices=[(0, 'C-2'), (1, '0-1'), (2, 'D-2'), (3, 'D-7'), (4, 'D-10'), (5, 'F-1'), (6, 'A-7'), (7, 'A-1'), (8, 'A-2'), (9, 'F-1')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimientopropietario',
            name='visa',
            field=models.BooleanField(default=False),
        ),
    ]
