# Generated by Django 5.2.4 on 2025-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_movimientoarrendatario_residente_inmobiliario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoarrendatario',
            name='fecha_visa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoconviviente',
            name='fecha_visa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientopropietario',
            name='fecha_visa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
