# Generated by Django 5.2.4 on 2025-09-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_movimientoarrendatario_fecha_visa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendatario',
            name='residente_inmobiliario',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='tipo_visa',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='conviviente',
            name='residente_inmobiliario',
        ),
        migrations.RemoveField(
            model_name='conviviente',
            name='tipo_visa',
        ),
        migrations.RemoveField(
            model_name='conviviente',
            name='visa',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='residente_inmobiliario',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='tipo_visa',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='visa',
        ),
    ]
